// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Div: typeof import('vue-termui')['TuiBox']
    Input: typeof import('./src/components/Input.vue')['default']
    Output: typeof import('./src/components/Output.vue')['default']
  }
}
